
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rizqy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chika_username = new javax.swing.JTextField();
        chika_password = new javax.swing.JPasswordField();
        chika_login1 = new javax.swing.JButton();
        chika_keterangan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(chika_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 30));

        chika_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(chika_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, 30));

        chika_login1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chika_login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Unlock-icon.png"))); // NOI18N
        chika_login1.setText("LOGIN");
        chika_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_login1ActionPerformed(evt);
            }
        });
        jPanel1.add(chika_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 40));

        chika_keterangan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chika_keterangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Arrow-next-2-icon.png"))); // NOI18N
        chika_keterangan.setText("KETERANGAN");
        chika_keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_keteranganActionPerformed(evt);
            }
        });
        jPanel1.add(chika_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("TI MSU CLASS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 420, 200));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sekul img.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chika_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_login1ActionPerformed
        // TODO add your handling code here:
         String username="admin"; // Mendeklarasikan dan menginisialisasi variabel username dengan nilai "admin"
         String password="123"; // Mendeklarasikan dan menginisialisasi variabel password dengan nilai "123"
            if(username.equalsIgnoreCase(chika_username.getText()) && // Mengecek apakah nilai username sama dengan input dari field chika_username tanpa memperhatikan huruf besar/kecil
            password.equalsIgnoreCase(chika_password.getText())){ // Mengecek apakah nilai password sama dengan input dari field chika_password tanpa memperhatikan huruf besar/kecil
            this.setVisible(false); // Menyembunyikan frame atau jendela saat ini
            new MenuUtama().setVisible(true); // Membuka jendela MenuUtama
            javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN"); // Menampilkan pesan dialog bahwa login berhasil
            dispose(); // Menutup jendela saat ini
                }else{
                    javax.swing.JOptionPane.showMessageDialog(null, "MAAF USER DAN PASSWORD ANDA SALAH", "Error", // Menampilkan pesan dialog bahwa login gagal dengan tipe pesan error
                    JOptionPane.ERROR_MESSAGE);
                    chika_username.setText("UserName"); // Mengatur ulang field chika_username dengan teks "UserName"
                    chika_password.setText("password"); // Mengatur ulang field chika_password dengan teks "password"
                    chika_username.requestFocus(); // Mengatur fokus kembali ke field chika_username
}

    }//GEN-LAST:event_chika_login1ActionPerformed

    private void chika_keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_keteranganActionPerformed
        // TODO add your handling code here:
        Keterangan keterangan = new Keterangan(); // Ganti Keterangan dengan nama kelas JFrame keterangan Anda
        keterangan.setVisible(true);
    }//GEN-LAST:event_chika_keteranganActionPerformed

    private void chika_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chika_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { // Menempatkan Runnable ke dalam antrian event GUI
            public void run() { // Metode run() dari Runnable yang akan dijalankan di thread event-dispatching
                new Login().setVisible(true); // Membuat instance dari frame Login dan membuatnya terlihat (menampilkan UI login)
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton chika_keterangan;
    private javax.swing.JButton chika_login1;
    private javax.swing.JPasswordField chika_password;
    private javax.swing.JTextField chika_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
