
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rizqy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chika_username = new javax.swing.JTextField();
        chika_password = new javax.swing.JPasswordField();
        chika_login1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chika_keterangan = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(chika_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, 30));
        jPanel1.add(chika_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, 30));

        chika_login1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chika_login1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\assets\\Unlock-icon.png")); // NOI18N
        chika_login1.setText("LOGIN");
        chika_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_login1ActionPerformed(evt);
            }
        });
        jPanel1.add(chika_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("TI MSU CLASS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        chika_keterangan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chika_keterangan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\assets\\Unlock-icon.png")); // NOI18N
        chika_keterangan.setText("KETEERANGAN");
        chika_keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_keteranganActionPerformed(evt);
            }
        });
        jPanel1.add(chika_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 440, 210));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\sekul img.png")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chika_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_login1ActionPerformed
        // TODO add your handling code here:
          String username="salam";
        String password="12345";
        if(username.equalsIgnoreCase(chika_username.getText())&&
            password.equalsIgnoreCase(chika_password.getText())){
            this.setVisible(false);
            new MenuUtama().setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN");
            dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "MAAF USER DAN PASSWORD ANDA SALAH", "Error",
                        JOptionPane.ERROR_MESSAGE);
            chika_username.setText("UserName");
            chika_password.setText("password");
            chika_username.requestFocus();
        }
    }//GEN-LAST:event_chika_login1ActionPerformed

    private void chika_keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_keteranganActionPerformed
        // TODO add your handling code here:
        Keterangan keterangan = new Keterangan(); // Ganti Keterangan dengan nama kelas JFrame keterangan Anda
        keterangan.setVisible(true);
    // Atau, jika JFrame keterangan sudah ditampilkan sebelumnya dan hanya perlu di-focus
    // keteranganFrame.requestFocus();
    }//GEN-LAST:event_chika_keteranganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton chika_keterangan;
    private javax.swing.JButton chika_login1;
    private javax.swing.JPasswordField chika_password;
    private javax.swing.JTextField chika_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
