/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rizqy
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chika_mahasiswa = new javax.swing.JButton();
        chika_user = new javax.swing.JButton();
        chika_uangkas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        chika_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("MENU UTAMA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Mahasiswa");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("User");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        chika_mahasiswa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chika_mahasiswa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\assets\\image upload.png")); // NOI18N
        chika_mahasiswa.setText("Mahasiswa");
        chika_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_mahasiswaActionPerformed(evt);
            }
        });
        jPanel2.add(chika_mahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        chika_user.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chika_user.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\assets\\update.png")); // NOI18N
        chika_user.setText("User");
        chika_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_userActionPerformed(evt);
            }
        });
        jPanel2.add(chika_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));

        chika_uangkas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chika_uangkas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\assets\\new-icon.png")); // NOI18N
        chika_uangkas.setText("Uang Kas");
        chika_uangkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_uangkasActionPerformed(evt);
            }
        });
        jPanel2.add(chika_uangkas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Uang Kas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 290, 190));

        chika_logout.setText("LOGOUT");
        chika_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(chika_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\sekul img.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chika_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_mahasiswaActionPerformed
        // TODO add your handling code here:
            new Mahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_chika_mahasiswaActionPerformed

    private void chika_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_logoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
        javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGOUT");
    }//GEN-LAST:event_chika_logoutActionPerformed

    private void chika_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_userActionPerformed
        // TODO add your handling code here:
       new user ().setVisible(true);
        dispose();
    }//GEN-LAST:event_chika_userActionPerformed

    private void chika_uangkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_uangkasActionPerformed
        // TODO add your handling code here:
         new UangKas ().setVisible(true);
        dispose();
    }//GEN-LAST:event_chika_uangkasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chika_logout;
    private javax.swing.JButton chika_mahasiswa;
    public javax.swing.JButton chika_uangkas;
    private javax.swing.JButton chika_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private static class User {

        public User() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
