/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Rizqy
 */
public class UangKas extends javax.swing.JFrame {
     private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t, keterangan;
    private DefaultTableModel dtm;



    /**
     * Creates new form uangkas
     */
    public UangKas() {
        initComponents();
        setTitle("LAPORAN UANGKAS");
        koneksi();
        kosongkan();
        tabel();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
            (screenSize.width - frameSize.width) / 3,
            (screenSize.height - frameSize.height) / 4);
    }
    
    
    private void koneksi (){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasikelas?useSSL=false&serverTimezone=UTC", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    
    private void kosongkan(){
     chika_no.setText("");
     chika_tanggal.setDate(null);
     chika_nama.setText("");
     chika_keterangan.setText("");
     chika_pembayaran.setText("");
     chika_pengeluaran.setText("");
     chika_saldoakhir.setText("");
     pembayaran.setSelected(false);
     pengeluaran.setSelected(false);
     chika_no.requestFocus();
    }
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("No");
        t.addColumn("Tanggal");
        t.addColumn("Nama");
        t.addColumn("Pemasukan");
        t.addColumn("Pengeluaran");
        t.addColumn("SaldoAkhir");
        t.addColumn("Keterangan");
        chika_table.setModel(t); try{ res= stat.executeQuery("select * from uangkas");
    while (res.next()) {
    t.addRow(new Object[]{ 
      res.getString("No"),
      res.getString("Tanggal"),
      res.getString("Nama"),
      res.getString("Pemasukan"),
      res.getString("Pengeluaran"),
      res.getString("SaldoAkhir"),
      res.getString("Keterangan")
        });}
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chika_saldoakhir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chika_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        chika_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chika_keterangan = new javax.swing.JTextField();
        pengeluaran = new javax.swing.JCheckBox();
        pembayaran = new javax.swing.JCheckBox();
        chika_no = new javax.swing.JTextField();
        chika_pembayaran = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        chika_pengeluaran = new javax.swing.JTextField();
        chika_search = new javax.swing.JButton();
        chika_edit = new javax.swing.JButton();
        chika_simpan = new javax.swing.JButton();
        chika_clear = new javax.swing.JButton();
        chika_hapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chika_lihat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chika_table = new javax.swing.JTable();
        chika_menu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("NO.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        chika_saldoakhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chika_saldoakhirKeyTyped(evt);
            }
        });
        jPanel1.add(chika_saldoakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tanggal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, -1, -1));
        jPanel1.add(chika_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 63, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, -1, -1));
        jPanel1.add(chika_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 110, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Keterangan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, -1, -1));
        jPanel1.add(chika_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 150, 120, -1));

        pengeluaran.setText("Pengeluaran");
        pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranActionPerformed(evt);
            }
        });
        jPanel1.add(pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 54, 97, 31));

        pembayaran.setText("Pembayaran");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 12, 97, 30));

        chika_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_noActionPerformed(evt);
            }
        });
        jPanel1.add(chika_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 16, 120, -1));

        chika_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_pembayaranActionPerformed(evt);
            }
        });
        chika_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chika_pembayaranKeyTyped(evt);
            }
        });
        jPanel1.add(chika_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, -1));

        jTextField6.setText("jTextField1");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, -1));

        chika_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_pengeluaranActionPerformed(evt);
            }
        });
        chika_pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chika_pengeluaranKeyTyped(evt);
            }
        });
        jPanel1.add(chika_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 120, -1));

        chika_search.setText("SEARCH");
        chika_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_searchActionPerformed(evt);
            }
        });
        jPanel1.add(chika_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, 80));

        chika_edit.setText("EDIT");
        chika_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_editActionPerformed(evt);
            }
        });
        jPanel1.add(chika_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 80));

        chika_simpan.setText("SIMPAN");
        chika_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(chika_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, 80));

        chika_clear.setText("CLEAR");
        chika_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_clearActionPerformed(evt);
            }
        });
        jPanel1.add(chika_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, 80));

        chika_hapus.setText("HAPUS");
        chika_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(chika_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 100, 80));

        jLabel5.setText("Rp.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel6.setText("Rp,");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel7.setText("Saldo Akhir");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jTextField8.setText("10.000");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel8.setText("Uang Kas/2Minggu");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel9.setText("Rp.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        chika_lihat.setText("lihat");
        chika_lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_lihatActionPerformed(evt);
            }
        });
        jPanel1.add(chika_lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 580, 320));

        chika_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        chika_table.setShowHorizontalLines(true);
        chika_table.setShowVerticalLines(true);
        chika_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chika_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(chika_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 580, 100));

        chika_menu.setText("MENU");
        chika_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chika_menuActionPerformed(evt);
            }
        });
        getContentPane().add(chika_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rizqy\\Downloads\\sekul img.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void chika_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_noActionPerformed
        // TODO add your handling code here:
         try{
            res=stat.executeQuery("select * from uangkas where "+ "No='" + chika_no.getText()
                +"'" ); while (res.next())
                { chika_tanggal.setDate (res.getDate("Tanggal"));
                chika_nama.setText(res.getString("Nama"));
                chika_pembayaran.setText(res.getString("Pemasukan"));
                chika_pengeluaran.setText(res.getString("Pengeluaran"));
                chika_saldoakhir.setText(res.getString("SaldoAkhir"));
                chika_keterangan.setText(res.getString("Keterangan"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_chika_noActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
        keterangan = "Uang Masuk";
        pengeluaran.setSelected(false);
        chika_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranActionPerformed
        // TODO add your handling code here:
        keterangan = "Uang Keluar";
        pembayaran.setSelected(false);
        chika_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pengeluaranActionPerformed

    private void chika_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_simpanActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
    if (chika_no.getText().isEmpty() || chika_tanggal.getDate() == null || chika_nama.getText().isEmpty() ||
            chika_pembayaran.getText().isEmpty() && chika_pengeluaran.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Mohon lengkapi semua data");
        return;
    }

    // Validasi No harus berupa angka
    try {
        int no = Integer.parseInt(chika_no.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Nomor harus berupa angka");
        return;
    }

    try {
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String Tanggal = fm.format(chika_tanggal.getDate());

        // Pastikan format tanggal sesuai dengan yang diharapkan

        String sql = "INSERT INTO uangkas (No, Tanggal, Nama, Pemasukan, Pengeluaran, SaldoAkhir, Keterangan) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, chika_no.getText());
        st.setString(2, Tanggal);
        st.setString(3, chika_nama.getText());
        st.setString(4, chika_pembayaran.getText().isEmpty() ? "0" : chika_pembayaran.getText());
        st.setString(5, chika_pengeluaran.getText().isEmpty() ? "0" : chika_pengeluaran.getText());
        st.setString(6, chika_saldoakhir.getText());
        st.setString(7, chika_keterangan.getText());

        int result = st.executeUpdate();
        System.out.println("Rows affected: " + result);

        kosongkan();
        tabel(); // Refresh table after saving
        JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage());
    }

    }//GEN-LAST:event_chika_simpanActionPerformed

    private void chika_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_editActionPerformed
        // TODO add your handling code here:
          if (chika_no.getText().isEmpty() || chika_tanggal.getDate() == null || chika_nama.getText().isEmpty() ||
                (chika_pembayaran.getText().isEmpty() && chika_pengeluaran.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua data");
            return;
        }

        try {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String Tanggal = fm.format(chika_tanggal.getDate());

            String sql = "UPDATE uangkas SET Tanggal = ?, Nama = ?, Pemasukan = ?, Pengeluaran = ?, SaldoAkhir = ?, Keterangan = ? WHERE No = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, Tanggal);
            st.setString(2, chika_nama.getText());
            st.setString(3, chika_pembayaran.getText().isEmpty() ? "0" : chika_pembayaran.getText());
            st.setString(4, chika_pengeluaran.getText().isEmpty() ? "0" : chika_pengeluaran.getText());
            st.setString(5, chika_saldoakhir.getText());
            st.setString(6, chika_keterangan.getText());
            st.setString(7, chika_no.getText());
            st.executeUpdate();
            kosongkan();
            tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diupdate: " + e.getMessage());
        }
    }//GEN-LAST:event_chika_editActionPerformed

    private void chika_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_clearActionPerformed
        // TODO add your handling code here:
            if (chika_no.getText().isEmpty() || chika_tanggal.getDate() == null || chika_nama.getText().isEmpty() ||
                (chika_pembayaran.getText().isEmpty() && chika_pengeluaran.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua data");
            return;
        }
         kosongkan();
    }//GEN-LAST:event_chika_clearActionPerformed

    private void chika_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_hapusActionPerformed
        // TODO add your handling code here:
            if (chika_no.getText().isEmpty() || chika_tanggal.getDate() == null || chika_nama.getText().isEmpty() ||
                (chika_pembayaran.getText().isEmpty() && chika_pengeluaran.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua data");
            return;
        }
        
         int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
         try{
             String sql="delete from uangkas where No='"+chika_no.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new UangKas().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
    }//GEN-LAST:event_chika_hapusActionPerformed

    private void chika_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_searchActionPerformed
        // TODO add your handling code here:
            if (chika_no.getText().isEmpty() || chika_tanggal.getDate() == null || chika_nama.getText().isEmpty() ||
                (chika_pembayaran.getText().isEmpty() && chika_pengeluaran.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua data");
            return;
        }
        try {
    res=stat.executeQuery("select * from uangkas where "+ "No='" +chika_no.getText()
    +"'" ); while (res.next())
    { chika_tanggal.setDate(res.getDate("Tanggal"));
      chika_nama.setText(res.getString("Nama"));
      chika_pembayaran.setText(res.getString("Pemasukan"));
      chika_pengeluaran.setText(res.getString("Pengeluaran"));
      chika_saldoakhir.setText(res.getString("SaldoAkhir"));
      chika_keterangan.setText(res.getString("Keterangan"));
    }
}catch (Exception e) {
JOptionPane.showMessageDialog(rootPane, e);
}
    }//GEN-LAST:event_chika_searchActionPerformed

    private void chika_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_menuActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_chika_menuActionPerformed

    private void chika_lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_lihatActionPerformed
        // TODO add your handling code here:
        new TableMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_chika_lihatActionPerformed

    private void chika_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chika_tableMouseClicked
        // TODO add your handling code here:
        int i = chika_table.getSelectedRow();
    if(i==-1){
    return;
    }
    String code = (String)chika_table.getValueAt(i,0);
    String code1 = (String)chika_table.getValueAt(i,1);
    String code2 = (String)chika_table.getValueAt(i,2);
    String code3 = (String)chika_table.getValueAt(i,3);
    String code4 = (String)chika_table.getValueAt(i,4);
    String code5 = (String)chika_table.getValueAt(i,5);
    String code6 = (String)chika_table.getValueAt(i,6);
    
    chika_no.setText(code);
    chika_tanggal.setDateFormatString(code1);
    chika_nama.setText(code2);
    chika_pembayaran.setText(code3);
    chika_pengeluaran.setText(code4);
    chika_saldoakhir.setText(code5);
    chika_keterangan.setText(code6);
        
    }//GEN-LAST:event_chika_tableMouseClicked

    private void chika_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chika_pembayaranActionPerformed

    private void chika_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chika_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chika_pengeluaranActionPerformed

    private void chika_pembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chika_pembayaranKeyTyped
        // TODO add your handling code here:
           char chika=evt.getKeyChar();
        if(!(Character.isDigit(chika)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_chika_pembayaranKeyTyped

    private void chika_pengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chika_pengeluaranKeyTyped
        // TODO add your handling code here:
         char chika=evt.getKeyChar();
        if(!(Character.isDigit(chika)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_chika_pengeluaranKeyTyped

    private void chika_saldoakhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chika_saldoakhirKeyTyped
        // TODO add your handling code here:
        char chika=evt.getKeyChar();
        if(!(Character.isDigit(chika)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_chika_saldoakhirKeyTyped

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangKas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chika_clear;
    private javax.swing.JButton chika_edit;
    private javax.swing.JButton chika_hapus;
    private javax.swing.JTextField chika_keterangan;
    private javax.swing.JButton chika_lihat;
    private javax.swing.JButton chika_menu;
    public javax.swing.JTextField chika_nama;
    private javax.swing.JTextField chika_no;
    private javax.swing.JTextField chika_pembayaran;
    private javax.swing.JTextField chika_pengeluaran;
    private javax.swing.JTextField chika_saldoakhir;
    private javax.swing.JButton chika_search;
    private javax.swing.JButton chika_simpan;
    private javax.swing.JTable chika_table;
    private com.toedter.calendar.JDateChooser chika_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JCheckBox pembayaran;
    private javax.swing.JCheckBox pengeluaran;
    // End of variables declaration//GEN-END:variables
}
